//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Account_Manage {
    protected global::System.Web.UI.WebControls.PlaceHolder successMessage;
    protected global::System.Web.UI.WebControls.PlaceHolder setPassword;
    protected global::System.Web.UI.WebControls.TextBox password;
    protected global::System.Web.UI.WebControls.TextBox confirmPassword;
    protected global::System.Web.UI.WebControls.PlaceHolder changePasswordHolder;
    protected global::System.Web.UI.WebControls.TextBox CurrentPassword;
    protected global::System.Web.UI.WebControls.TextBox NewPassword;
    protected global::System.Web.UI.WebControls.TextBox ConfirmNewPassword;
}
