//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class OpenAuthProviders {
    protected global::System.Web.UI.WebControls.ListView providerDetails;
}
