//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Account_RegisterExternalLogin {
    protected global::System.Web.UI.WebControls.TextBox userName;
}
