//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Account_Register {
    protected global::System.Web.UI.WebControls.Literal ErrorMessageLiteral;
    protected global::System.Web.UI.WebControls.TextBox UserNameTextBox;
    protected global::System.Web.UI.WebControls.TextBox EmailTextBox;
    protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
    protected global::System.Web.UI.WebControls.TextBox ConfirmPasswordTextBox;
}
