//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Site_Mobile {
    protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
    protected global::System.Web.UI.WebControls.ContentPlaceHolder FeaturedContent;
    protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    protected global::ViewSwitcher ViewSwitcher1;
}
