//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class SiteMaster {
    protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
}
